export const girlfriendResponses = [
	'Of course, I love spending time with you',
	'You look beautiful today',
	"I'm always here if you need to talk",
	"Let's watch your favorite movie tonight",
	'I love the way you laugh',
	'Your happiness means a lot to me',
	"I'm proud of everything you've accomplished",
	'Of course I want to hear about your day',
	'You can always count on me',
	"Let's order your favorite food tonight",
	'I love hearing your ideas',
	'I trust you completely',
	'You make my life better',
	"I'm grateful to have you in my life",
	"I'll support you no matter what",
	"Let's plan a weekend getaway",
	'You always know how to make me smile',
	'I appreciate everything you do',
	'Your opinion matters to me',
	'I love how passionate you are',
	'I missed you today',
	"I'm sorry if I upset you",
	"Let's talk about it and work things out",
	"You're my favorite person",
	'I love your sense of humor',
	"I'm always here to listen",
	'You inspire me every day',
	'I love your creativity',
	"I'm lucky to have you",
	"Let's try that new restaurant you mentioned",
	'I love your cooking',
	"You're so thoughtful",
	"I'm excited for our future together",
	"Let's make some new memories",
	'I love your style',
	"You're important to me",
	'I love how caring you are',
	"I'm here for you, always",
	"Let's cuddle and watch a show",
	'You make everything better',
	'I love your smile',
	"You're the best thing that's ever happened to me",
	'I love your energy',
	"I'm happy just being with you",
	"Let's do something fun together",
	"You're so talented",
	'I love your ambition',
	'I love you sosososososososo much <3!',
	'I love your confidence',
	"I'm so glad we met",
	'You make me want to be a better person',
	'I love your kindness',
	"You're amazing just the way you are",
	'I love going on adventures with you',
	"Let's try something new together",
	"You're so understanding",
	'I love your honesty',
	'You always know what to say',
	'I love your hugs',
	"You're my favorite person to talk to",
	'I love how you see the world',
	"You're so supportive",
	'I love your laugh',
	'You make me feel special',
	'I love how we can talk about anything',
	"You're my partner in everything",
	'I love how you challenge me',
	"You're the first person I think of in the morning",
	'I love sharing my life with you',
	"You're so patient",
	'I love your curiosity',
	"You're my home",
	'I love how you care about others',
	"You're so smart",
	'I love how adventurous you are',
	'You make every day brighter',
	'I love how you surprise me',
	"You're my favorite adventure",
	'I love how we laugh together',
	"You're the reason I smile",
	'I love your warmth',
	"You're so genuine",
	'I love how you listen',
	"You're my sunshine",
	'I love your determination',
	"You're so interesting",
	'I love your stories',
	"You're my everything",
	'I love how you make me feel',
	"You're so easy to talk to",
	'I love your perspective',
	"You're so creative",
	'I love being silly with you',
	"You're the best part of my day",
	'I love your enthusiasm',
	"You're so thoughtful",
	'I love how you care for me',
	"You're perfect to me",
	'I love our inside jokes',
	"You're my favorite hello and hardest goodbye"
];

export function createResponse(): string {
	const response = girlfriendResponses[Math.floor(Math.random() * girlfriendResponses.length)];
	return response;
}
