export const girlfriendResponses = [
	'I love spending time with you',
	'You look beautiful',
	"I'm always here if you need to talk",
	'Your voice is calming',
	'Your happiness makes me happy',
	"I'm proud of everything you've accomplished",
	'I trust you completely',
	'You make my life better',
	"I'm grateful to have you in my life",
	"I'll be with you no matter what",
	'I want to come back to Toronto and see you',
	'You always know how to make me smile',
	'I appreciate everything you do',
	'I missed you today',
	"I'm sorry if I upset you",
	"You're my favorite hitler",
	'I love your jokes',
	"I'm always here to listen",
	"I'm lucky to have you",
	'I love your cooking',
	'I love your style',
	"You're important to me",
	"I'm here for you, always",
	"Let's cuddle and hold you near me",
	'You make everything better',
	'I love your smile',
	"You're the best thing that's ever happened to me",
	"I'm happy just being with you",
	'I love you sosososososososo much <3!',
	"I'm so glad we met",
	'You make me want to be a better person',
	"You're amazing just the way you are",
	'I love going on adventures with you',
	"You're so understanding",
	'I love your honesty',
	'You always know what to say',
	'I love your cuddles',
	"You're my favorite person to talk to",
	'I love your laugh',
	'I love how we can talk about anything',
	"You're the first person I think of in the morning",
	'I love sharing my life with you',
	'You make every day brighter',
	"You're the reason I smile",
	'I love your warmth',
	"You're so genuine",
	"You're so easy to talk to",
	'I love being silly with you',
	"You're perfect to me",
	"Daily reminder, don't gamble",
	'Meow'
];

export const decisionResponses = [
	'Yes, do it!',
	'No, you should reconsider',
	"Daily reminder, don't gamble",
	'Meow',
	'I think we should go for it!',
	"Let's go GAMBLING!!!",
	'Praying 🙏',
	'I trust your judgment',
	'Better not to',
	'Maybe another time',
	'Maybe sleep on it first',
	'Maybe ask someone else for their opinion',
	"No, this doesn't feel right",
	'Could go either way, honestly',
	'Absolutely yes!',
	'Go for it!',
	'100% yes',
	'Yes, trust your instincts on this one',
	'If you have to ask, you already know the answer',
	'Signs point to yes',
	'Better not tell you now',
	'Ask again later',
	'Cannot predict now',
	'Concentrate and ask again',
	'My sources say no',
	'Outlook not so good',
	'Very doubtful',
	'Without a doubt',
	'My reply is no',
	'Most likely',
	'It is certain',
	'It is decidedly so',
	'Definitely not',
	'The stars say yes',
	'Not worth the risk',
	'Proceed with caution',
	'All signs point to yes',
	'Definitely worth a try',
	'Not the best idea right now',
	'Trust your gut on this one',
	'Think about the consequences first',
	'You might regret it later',
	"You'll thank yourself later if you do it",
	'Sounds like a plan!',
	"I wouldn't if I were you",
	'Why not?',
	'Give it a shot!',
	"The timing isn't right",
	"It's a trap!",
	'You only live once'
];

export function createResponse(): string {
	const response = girlfriendResponses[Math.floor(Math.random() * girlfriendResponses.length)];
	return response;
}

export function createDecisionResponse(): string {
	const response = decisionResponses[Math.floor(Math.random() * decisionResponses.length)];
	return response;
}
