services:
  app:
    container_name: valentina-app
    working_dir: /app
    build:
      context: ./
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '5'
    restart: always

  nginx:
    container_name: valentina-nginx
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/ssl/private:/etc/ssl/private
    ports:
      - 8008:80
      - 44300:443
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '5'
    restart: always
