services:
  valentina-app:
    container_name: valentina-app
    working_dir: /app
    build:
      context: ./
    expose:
      - '3000'
    networks:
      - shared-proxy
      - default
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '5'
    restart: always

networks:
  shared-proxy:
    external: true
